# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 0.1.0
  maturin_min: 1.1.0
  maturin_max: 2.0.0

package:
  name: rloop
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/r/rloop/rloop-${{ version }}.tar.gz
  sha256: ab9f98f6e4e1df18dd7399a96024f8cfbe1d3c2e92e7177aaa53fb68d3f075b6

build:
  number: 0
  skip: win
  script:
    file: build-rloop

requirements:
  build:
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - crossenv
        - maturin >=${{ maturin_min }},<${{ maturin_max }}
  host:
    - maturin >=${{ maturin_min }},<${{ maturin_max }}
    - pip
    - python
  run:
    - python

tests:
  - python:
      imports: rloop
      pip_check: true
  - files:
      source:
        - pyproject.toml
        - tests/
    requirements:
      run:
        - coverage
        - pytest >=7.4.2,<7.5.0
        - pytest-asyncio >=0.21.1,<0.22.0
    script:
      - coverage run --source=rloop --branch -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=38

about:
  summary: An asyncio event loop implemented in Rust
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/gi0baro/rloop

extra:
  recipe-maintainers:
    - bollwyvl
